### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by erer2727** [IRPTeam/eFaturaXSLT#1]
Merhaba logo ekleyemedim yardımcı olurmusunuz lütfen.

**Comment by erer2727** [comment]
Ayrıca Banka Iban Bilgilerimizi eklermisiniz?

**Comment by DitriXNew** [comment]
Hi. You can fill 3 pictures in this fields:
.CompanyLogo
.Sign
.GIBLogo 

If you want fill with empty image, you can do like this:

```css
.Sign {
    content: url("data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=");
    width: 120px;
    height: 120px;
}
```
In `content` you have to fill base64 you picture.
`data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=` - this is just empty pixel

If you want to fill with your picture, then you need to get base64 your file.
You can do it on this site [https://base64.guru/converter/encode/image](https://base64.guru/converter/encode/image)
Just set the URL or get it from a local file, select the type as 'URI,' and you'll get a base64 preview of your picture:
![image](https://github.com/IRPTeam/eFaturaXSLT/assets/11927866/c147fbcb-3317-468a-9d1e-8a21a5cfd0c1)
